### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by emogg** [abetusk/gbr2ngc#11]
Is there more detailed documentation on the command line arguments?

**Comment by abetusk** [comment]
@emogg, Thanks for you interest!

I've added a [documentation page](https://github.com/abetusk/gbl2ngc/blob/release/doc/Documentation.md) that hopefully addresses your concerns.

I'm familiar with the program and the different components so I might be too close to realize how confusing the program and options might be.  Could you look this over and see if this looks reasonable to you?  Could you also suggest any additions if you find it lacking?

I'm going to close this issue but feel free to add more detail to this Issue or create a new one with more detailed information.
