### ISSUE TITLE
blank lines are not skipped

### ISSUE THREAD

**Issue by emogg** [abetusk/gbr2ngc#14]
Blank lines are in the gerber files generated by kicad and gbl2ngc aborts

PARSE ERROR: unknown function code at line 12 ''

**Comment by emogg** [comment]
My mistake, these gerbers were generated by EasyEDA, but the result is the same

**Comment by abetusk** [comment]
Thanks @emogg for the bug report and thanks @DariusMontez for the fix. See the #15 for more details and a simple test to make sure the bug fix went through
