### ISSUE TITLE
Implement circle arcs (G2/G3)

### ISSUE THREAD

**Issue by abetusk** [abetusk/gbr2ngc#2]
This has been started by adding the `quadrent_mode` to the `gerber_state_t` structure, but the actual parsing and realization of the G2 and G3 (clockwise/counter-clockwise circle arc commands, resp.) still needs to be implemented.

**Comment by abetusk** [comment]
To be added with the `gerber-extensions` branch (in progress by me).

**Comment by abetusk** [comment]
resolved by 2e149e48359e55763310077dbe761446792523f1

**Comment by XRay3D** [comment]
https://github.com/XRay3D/GERBER_X2
