### ISSUE TITLE
Curved paths are missing from silkscreen

### ISSUE THREAD

**Issue by jes** [abetusk/gbr2ngc#22]
I'm not sure precisely what the problem is here, but I have observed that the G-code for my silkscreens is missing the curved paths.

I've attached a (zipped, to appease github) Gerber file that causes the problem, along with a screenshot of the G-code path as rendered by FreeCAD, and the PCB as rendered by KiCad.

Curiously, the text is fine. It is only the nub on the graphic that is a problem. I wonder if the text is composed of line segments and the nub is a curved path?

This is not a big deal for me, just an observation. The silkscreen is more than usable even without the little nub.

[nubgerb.zip](https://github.com/abetusk/gbr2ngc/files/5990995/nubgerb.zip)
![freecad](https://user-images.githubusercontent.com/297425/108108072-0532a380-7088-11eb-8f99-dec427c04cec.png)
![kicad](https://user-images.githubusercontent.com/297425/108108076-05cb3a00-7088-11eb-9e33-50b616385462.png)

**Comment by jes** [comment]
Line 29 of the gerber file appears to be a curved path indeed:

`G02X126254000Y-72838000I-1000000J0D01*`

This looks very similar to the actual G-code required to form a curved path, so it may be quite an easy fix. Not sure. Maybe isolation routing complicates it. It might be easiest to preprocess the curved path from the Gerber into a bunch of line segments.

**Comment by abetusk** [comment]
Oof, well, this is embarrassing. Apparently I hadn't implemented `G02` and `G03` for straight line segments.

The parsing code is there and, if I remember correctly, I did the interpolation for regions, I just never got around to adding it in for the linear segments for some reason.

At any rate, it looks to be a quick fix as most of the interpolation etc. is implemented, so it's just about parsing the corresponding `G02` and `G03` lines correctly.

FYI, the engine for the polygon unions is Angus Johnson's [clipperlib](http://www.angusj.com/delphi/clipper.php) which acts on linearlized polygons, so all curves get interpolated to linear segments which are then fed into clipperlib to do polygon unionization.

I've included a picture of what the output is now. I've also added the `G03` functionality. This is minimally tested so please keep on the look out for any anomalous behavior.

![gerber_g03_confirm](https://user-images.githubusercontent.com/1406122/108146779-cb6b9800-709b-11eb-933e-ed180f6bbaa3.jpg)

Thanks for the test Gerber, this greatly speeds up debugging!

Would you mind if I included the Gerber file you provided in the examples or tests?

**Comment by jes** [comment]
Thanks, that was fast! Clipperlib sounds cool. The screenshot looks perfect. And yes you are welcome to use the Gerber file. I created it by creating a blank PCB in KiCad and adding a footprint for a DIP-4 socket or something like that.
