### ISSUE TITLE
cnc not waiting to reach safe z -> scares on milled piece

### ISSUE THREAD

**Issue by jappyjan** [abetusk/gbr2ngc#24]
i set safez to 2 but the cnc is not moving up and THEN to the next position,
instead it is doing both at the same time which results in the head not moving up quickly enough to prevent scars

**Comment by jappyjan** [comment]
same for the start of the milling process... the machine first moves down and then to the starting point which results in a large scar

**Comment by abetusk** [comment]
Could you provide a sample input Gerber file with it's corresponding converted GCode file so that I can see what's going on?

Could you also confirm what version of `gbr2ngc` you're using (`gbr2ngc -N`).
