### ISSUE TITLE
Implement aperture transformations (LP, LM, LR, LS)

### ISSUE THREAD

**Issue by abetusk** [abetusk/gbr2ngc#6]
| command | parameter |
|---|---|
| LP | Polarity |
| LM | Mirror |
| LR | Rotate |
| LS | Scale |

**Comment by abetusk** [comment]
Still not implemented but to be added to `gerber-extensions` (in progress by me).

**Comment by XRay3D** [comment]
https://github.com/XRay3D/GERBER_X2
